theme: jekyll-theme-midnight
thekindkeptn_version: "ttyd"
keptn_docs_version: "0.15.x"
ttyd_port: "7681"
job_executor_service_version: "0.2.0"
prometheus_service_version: "0.8.0"
image: "ghcr.io/podtato-head/podtatoserver"
good_version: "v0.1.1"
slow_version: "v0.1.2"
locust_image: "locustio/locust:2.8.6"
helm_image: "alpine/helm:3.9.0"
